# Generated by Django 3.2.9 on 2021-12-02 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_meter', models.IntegerField()),
                ('gallons', models.IntegerField()),
                ('price_per_gallon', models.IntegerField()),
                ('full_payment', models.IntegerField()),
                ('km_traveled', models.IntegerField()),
                ('km_per_gallon', models.IntegerField()),
                ('pay_per_km', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
