# Generated by Django 3.2.9 on 2021-12-02 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles_api', '0001_initial'),
        ('fuel_forms_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelform',
            name='vehicle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vehicles_api.vehicle'),
        ),
    ]
