# Generated by Django 3.2.9 on 2021-12-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_forms_api', '0002_fuelform_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelform',
            name='gallons',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fuelform',
            name='hour_meter',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fuelform',
            name='price_per_gallon',
            field=models.FloatField(),
        ),
    ]
