# Generated by Django 3.2.9 on 2021-12-11 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles_api', '0001_initial'),
        ('fuel_forms_api', '0003_auto_20211211_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelform',
            name='vehicle',
            field=models.ForeignKey(db_column='vehicle_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='vehicles_api.vehicle'),
        ),
    ]
