# Generated by Django 3.2.9 on 2021-12-11 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles_api', '0001_initial'),
        ('fuel_forms_api', '0005_alter_fuelform_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelform',
            name='vehicle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='vehicles_api.vehicle'),
        ),
    ]
