# Generated by Django 3.2.9 on 2021-12-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_forms_api', '0006_alter_fuelform_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelform',
            name='full_payment',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fuelform',
            name='km_per_gallon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fuelform',
            name='km_traveled',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fuelform',
            name='pay_per_km',
            field=models.FloatField(),
        ),
    ]
